/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:58 AM EDT 
//


package org.openfmb.xsd._2016._05.openfmb.regulatormodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2016._05.openfmb.regulatormodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegulatorSystem_QNAME = new QName("http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", "RegulatorSystem");
    private final static QName _RegulatorStatusProfile_QNAME = new QName("http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", "RegulatorStatusProfile");
    private final static QName _RegulatorReadingProfile_QNAME = new QName("http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", "RegulatorReadingProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2016._05.openfmb.regulatormodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegulatorStatusProfile }
     * 
     */
    public RegulatorStatusProfile createRegulatorStatusProfile() {
        return new RegulatorStatusProfile();
    }

    /**
     * Create an instance of {@link RegulatorReadingProfile }
     * 
     */
    public RegulatorReadingProfile createRegulatorReadingProfile() {
        return new RegulatorReadingProfile();
    }

    /**
     * Create an instance of {@link RegulatorSystem }
     * 
     */
    public RegulatorSystem createRegulatorSystem() {
        return new RegulatorSystem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegulatorSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", name = "RegulatorSystem")
    public JAXBElement<RegulatorSystem> createRegulatorSystem(RegulatorSystem value) {
        return new JAXBElement<RegulatorSystem>(_RegulatorSystem_QNAME, RegulatorSystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegulatorStatusProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", name = "RegulatorStatusProfile")
    public JAXBElement<RegulatorStatusProfile> createRegulatorStatusProfile(RegulatorStatusProfile value) {
        return new JAXBElement<RegulatorStatusProfile>(_RegulatorStatusProfile_QNAME, RegulatorStatusProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegulatorReadingProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/05/openfmb/regulatormodule", name = "RegulatorReadingProfile")
    public JAXBElement<RegulatorReadingProfile> createRegulatorReadingProfile(RegulatorReadingProfile value) {
        return new JAXBElement<RegulatorReadingProfile>(_RegulatorReadingProfile_QNAME, RegulatorReadingProfile.class, null, value);
    }

}
