//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.batterymodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for BatteryEventProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatteryEventProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="BatteryStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatteryStatus"/>
 *         &lt;element name="BatterySystem" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatterySystem"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatteryEventProfile", propOrder = {
    "batteryStatus",
    "batterySystem"
})
public class BatteryEventProfile
    extends Container
{

    @XmlElement(name = "BatteryStatus", required = true)
    protected BatteryStatus batteryStatus;
    @XmlElement(name = "BatterySystem", required = true)
    protected BatterySystem batterySystem;

    /**
     * Gets the value of the batteryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BatteryStatus }
     *     
     */
    public BatteryStatus getBatteryStatus() {
        return batteryStatus;
    }

    /**
     * Sets the value of the batteryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatteryStatus }
     *     
     */
    public void setBatteryStatus(BatteryStatus value) {
        this.batteryStatus = value;
    }

    /**
     * Gets the value of the batterySystem property.
     * 
     * @return
     *     possible object is
     *     {@link BatterySystem }
     *     
     */
    public BatterySystem getBatterySystem() {
        return batterySystem;
    }

    /**
     * Sets the value of the batterySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatterySystem }
     *     
     */
    public void setBatterySystem(BatterySystem value) {
        this.batterySystem = value;
    }

}
