//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.batterymodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for BatteryControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatteryControlProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="BatterySystem" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatterySystem"/>
 *         &lt;element name="BatterySystemControl" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatterySystemControl"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatteryControlProfile", propOrder = {
    "batterySystem",
    "batterySystemControl"
})
public class BatteryControlProfile
    extends Container
{

    @XmlElement(name = "BatterySystem", required = true)
    protected BatterySystem batterySystem;
    @XmlElement(name = "BatterySystemControl", required = true)
    protected BatterySystemControl batterySystemControl;

    /**
     * Gets the value of the batterySystem property.
     * 
     * @return
     *     possible object is
     *     {@link BatterySystem }
     *     
     */
    public BatterySystem getBatterySystem() {
        return batterySystem;
    }

    /**
     * Sets the value of the batterySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatterySystem }
     *     
     */
    public void setBatterySystem(BatterySystem value) {
        this.batterySystem = value;
    }

    /**
     * Gets the value of the batterySystemControl property.
     * 
     * @return
     *     possible object is
     *     {@link BatterySystemControl }
     *     
     */
    public BatterySystemControl getBatterySystemControl() {
        return batterySystemControl;
    }

    /**
     * Sets the value of the batterySystemControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatterySystemControl }
     *     
     */
    public void setBatterySystemControl(BatterySystemControl value) {
        this.batterySystemControl = value;
    }

}
