/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.batterymodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2015._12.openfmb.batterymodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BatteryEventProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatteryEventProfile");
    private final static QName _BatteryStatus_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatteryStatus");
    private final static QName _BatterySystemControl_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatterySystemControl");
    private final static QName _BatteryControlProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatteryControlProfile");
    private final static QName _BatterySystem_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatterySystem");
    private final static QName _BatteryReadingProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/batterymodule", "BatteryReadingProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2015._12.openfmb.batterymodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BatterySystem }
     * 
     */
    public BatterySystem createBatterySystem() {
        return new BatterySystem();
    }

    /**
     * Create an instance of {@link BatteryStatus }
     * 
     */
    public BatteryStatus createBatteryStatus() {
        return new BatteryStatus();
    }

    /**
     * Create an instance of {@link BatterySystemControl }
     * 
     */
    public BatterySystemControl createBatterySystemControl() {
        return new BatterySystemControl();
    }

    /**
     * Create an instance of {@link BatteryEventProfile }
     * 
     */
    public BatteryEventProfile createBatteryEventProfile() {
        return new BatteryEventProfile();
    }

    /**
     * Create an instance of {@link BatteryReadingProfile }
     * 
     */
    public BatteryReadingProfile createBatteryReadingProfile() {
        return new BatteryReadingProfile();
    }

    /**
     * Create an instance of {@link BatteryControlProfile }
     * 
     */
    public BatteryControlProfile createBatteryControlProfile() {
        return new BatteryControlProfile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatteryEventProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatteryEventProfile")
    public JAXBElement<BatteryEventProfile> createBatteryEventProfile(BatteryEventProfile value) {
        return new JAXBElement<BatteryEventProfile>(_BatteryEventProfile_QNAME, BatteryEventProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatteryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatteryStatus")
    public JAXBElement<BatteryStatus> createBatteryStatus(BatteryStatus value) {
        return new JAXBElement<BatteryStatus>(_BatteryStatus_QNAME, BatteryStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatterySystemControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatterySystemControl")
    public JAXBElement<BatterySystemControl> createBatterySystemControl(BatterySystemControl value) {
        return new JAXBElement<BatterySystemControl>(_BatterySystemControl_QNAME, BatterySystemControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatteryControlProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatteryControlProfile")
    public JAXBElement<BatteryControlProfile> createBatteryControlProfile(BatteryControlProfile value) {
        return new JAXBElement<BatteryControlProfile>(_BatteryControlProfile_QNAME, BatteryControlProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatterySystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatterySystem")
    public JAXBElement<BatterySystem> createBatterySystem(BatterySystem value) {
        return new JAXBElement<BatterySystem>(_BatterySystem_QNAME, BatterySystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatteryReadingProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", name = "BatteryReadingProfile")
    public JAXBElement<BatteryReadingProfile> createBatteryReadingProfile(BatteryReadingProfile value) {
        return new JAXBElement<BatteryReadingProfile>(_BatteryReadingProfile_QNAME, BatteryReadingProfile.class, null, value);
    }

}
