//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:19 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openfmb.xsd._2015._12.openfmb.batterymodule;
