/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:13 AM EDT 
//


package org.openfmb.xsd._2016._04.openfmb.shuntmodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2016._04.openfmb.shuntmodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ShuntControlProfile_QNAME = new QName("http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", "ShuntControlProfile");
    private final static QName _ShuntControl_QNAME = new QName("http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", "ShuntControl");
    private final static QName _ShuntSystem_QNAME = new QName("http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", "ShuntSystem");
    private final static QName _ShuntReadingProfile_QNAME = new QName("http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", "ShuntReadingProfile");
    private final static QName _ShuntStatusProfile_QNAME = new QName("http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", "ShuntStatusProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2016._04.openfmb.shuntmodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShuntReadingProfile }
     * 
     */
    public ShuntReadingProfile createShuntReadingProfile() {
        return new ShuntReadingProfile();
    }

    /**
     * Create an instance of {@link ShuntControl }
     * 
     */
    public ShuntControl createShuntControl() {
        return new ShuntControl();
    }

    /**
     * Create an instance of {@link ShuntControlProfile }
     * 
     */
    public ShuntControlProfile createShuntControlProfile() {
        return new ShuntControlProfile();
    }

    /**
     * Create an instance of {@link ShuntStatusProfile }
     * 
     */
    public ShuntStatusProfile createShuntStatusProfile() {
        return new ShuntStatusProfile();
    }

    /**
     * Create an instance of {@link ShuntSystem }
     * 
     */
    public ShuntSystem createShuntSystem() {
        return new ShuntSystem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShuntControlProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", name = "ShuntControlProfile")
    public JAXBElement<ShuntControlProfile> createShuntControlProfile(ShuntControlProfile value) {
        return new JAXBElement<ShuntControlProfile>(_ShuntControlProfile_QNAME, ShuntControlProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShuntControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", name = "ShuntControl")
    public JAXBElement<ShuntControl> createShuntControl(ShuntControl value) {
        return new JAXBElement<ShuntControl>(_ShuntControl_QNAME, ShuntControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShuntSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", name = "ShuntSystem")
    public JAXBElement<ShuntSystem> createShuntSystem(ShuntSystem value) {
        return new JAXBElement<ShuntSystem>(_ShuntSystem_QNAME, ShuntSystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShuntReadingProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", name = "ShuntReadingProfile")
    public JAXBElement<ShuntReadingProfile> createShuntReadingProfile(ShuntReadingProfile value) {
        return new JAXBElement<ShuntReadingProfile>(_ShuntReadingProfile_QNAME, ShuntReadingProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShuntStatusProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", name = "ShuntStatusProfile")
    public JAXBElement<ShuntStatusProfile> createShuntStatusProfile(ShuntStatusProfile value) {
        return new JAXBElement<ShuntStatusProfile>(_ShuntStatusProfile_QNAME, ShuntStatusProfile.class, null, value);
    }

}
