//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:13 AM EDT 
//


package org.openfmb.xsd._2016._04.openfmb.shuntmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * Instructs an end device (or an end device group) to perform a specified action.
 * 
 * <p>Java class for ShuntControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShuntControlProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="ShuntControl" type="{http://openfmb.org/xsd/2016/04/openfmb/shuntmodule}ShuntControl"/>
 *         &lt;element name="ShuntSystem" type="{http://openfmb.org/xsd/2016/04/openfmb/shuntmodule}ShuntSystem"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShuntControlProfile", propOrder = {
    "shuntControl",
    "shuntSystem"
})
public class ShuntControlProfile
    extends Container
{

    @XmlElement(name = "ShuntControl", required = true)
    protected ShuntControl shuntControl;
    @XmlElement(name = "ShuntSystem", required = true)
    protected ShuntSystem shuntSystem;

    /**
     * Gets the value of the shuntControl property.
     * 
     * @return
     *     possible object is
     *     {@link ShuntControl }
     *     
     */
    public ShuntControl getShuntControl() {
        return shuntControl;
    }

    /**
     * Sets the value of the shuntControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShuntControl }
     *     
     */
    public void setShuntControl(ShuntControl value) {
        this.shuntControl = value;
    }

    /**
     * Gets the value of the shuntSystem property.
     * 
     * @return
     *     possible object is
     *     {@link ShuntSystem }
     *     
     */
    public ShuntSystem getShuntSystem() {
        return shuntSystem;
    }

    /**
     * Sets the value of the shuntSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShuntSystem }
     *     
     */
    public void setShuntSystem(ShuntSystem value) {
        this.shuntSystem = value;
    }

}
