//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:09 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.securitymodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2015._12.openfmb.securitymodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SecurityEventProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/securitymodule", "SecurityEventProfile");
    private final static QName _SecurityEvent_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/securitymodule", "SecurityEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2015._12.openfmb.securitymodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityEvent }
     * 
     */
    public SecurityEvent createSecurityEvent() {
        return new SecurityEvent();
    }

    /**
     * Create an instance of {@link SecurityEventProfile }
     * 
     */
    public SecurityEventProfile createSecurityEventProfile() {
        return new SecurityEventProfile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityEventProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/securitymodule", name = "SecurityEventProfile")
    public JAXBElement<SecurityEventProfile> createSecurityEventProfile(SecurityEventProfile value) {
        return new JAXBElement<SecurityEventProfile>(_SecurityEventProfile_QNAME, SecurityEventProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/securitymodule", name = "SecurityEvent")
    public JAXBElement<SecurityEvent> createSecurityEvent(SecurityEvent value) {
        return new JAXBElement<SecurityEvent>(_SecurityEvent_QNAME, SecurityEvent.class, null, value);
    }

}
