//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:45 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.loadmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.IdentifiedObject;


/**
 * Generic user of energy - a  point of consumption on the power system model.
 * 
 * <p>Java class for EnergyConsumer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnergyConsumer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}IdentifiedObject">
 *       &lt;sequence>
 *         &lt;element name="operatingLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnergyConsumer", propOrder = {
    "operatingLimit"
})
public class EnergyConsumer
    extends IdentifiedObject
{

    protected String operatingLimit;

    /**
     * Gets the value of the operatingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingLimit() {
        return operatingLimit;
    }

    /**
     * Sets the value of the operatingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingLimit(String value) {
        this.operatingLimit = value;
    }

}
