//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:45 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.loadmodule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.StringMeasurement;


/**
 * <p>Java class for LoadStatusProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadStatusProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="EnergyConsumer" type="{http://openfmb.org/xsd/2015/12/openfmb/loadmodule}EnergyConsumer"/>
 *         &lt;element name="StringMeasurements" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}StringMeasurement" maxOccurs="100"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadStatusProfile", propOrder = {
    "energyConsumer",
    "stringMeasurements"
})
public class LoadStatusProfile
    extends Container
{

    @XmlElement(name = "EnergyConsumer", required = true)
    protected EnergyConsumer energyConsumer;
    @XmlElement(name = "StringMeasurements", required = true)
    protected List<StringMeasurement> stringMeasurements;

    /**
     * Gets the value of the energyConsumer property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyConsumer }
     *     
     */
    public EnergyConsumer getEnergyConsumer() {
        return energyConsumer;
    }

    /**
     * Sets the value of the energyConsumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyConsumer }
     *     
     */
    public void setEnergyConsumer(EnergyConsumer value) {
        this.energyConsumer = value;
    }

    /**
     * Gets the value of the stringMeasurements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringMeasurements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringMeasurements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringMeasurement }
     * 
     * 
     */
    public List<StringMeasurement> getStringMeasurements() {
        if (stringMeasurements == null) {
            stringMeasurements = new ArrayList<StringMeasurement>();
        }
        return this.stringMeasurements;
    }

}
