//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:45 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.loadmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for LoadControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadControlProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="EnergyConsumer" type="{http://openfmb.org/xsd/2015/12/openfmb/loadmodule}EnergyConsumer"/>
 *         &lt;element name="LoadControl" type="{http://openfmb.org/xsd/2015/12/openfmb/loadmodule}LoadControl"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadControlProfile", propOrder = {
    "energyConsumer",
    "loadControl"
})
public class LoadControlProfile
    extends Container
{

    @XmlElement(name = "EnergyConsumer", required = true)
    protected EnergyConsumer energyConsumer;
    @XmlElement(name = "LoadControl", required = true)
    protected LoadControl loadControl;

    /**
     * Gets the value of the energyConsumer property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyConsumer }
     *     
     */
    public EnergyConsumer getEnergyConsumer() {
        return energyConsumer;
    }

    /**
     * Sets the value of the energyConsumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyConsumer }
     *     
     */
    public void setEnergyConsumer(EnergyConsumer value) {
        this.energyConsumer = value;
    }

    /**
     * Gets the value of the loadControl property.
     * 
     * @return
     *     possible object is
     *     {@link LoadControl }
     *     
     */
    public LoadControl getLoadControl() {
        return loadControl;
    }

    /**
     * Sets the value of the loadControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadControl }
     *     
     */
    public void setLoadControl(LoadControl value) {
        this.loadControl = value;
    }

}
