/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:45 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.loadmodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2015._12.openfmb.loadmodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LoadStatusProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "LoadStatusProfile");
    private final static QName _LoadControl_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "LoadControl");
    private final static QName _LoadForecastProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "LoadForecastProfile");
    private final static QName _EnergyConsumer_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "EnergyConsumer");
    private final static QName _LoadControlProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "LoadControlProfile");
    private final static QName _LoadReadingProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/loadmodule", "LoadReadingProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2015._12.openfmb.loadmodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadStatusProfile }
     * 
     */
    public LoadStatusProfile createLoadStatusProfile() {
        return new LoadStatusProfile();
    }

    /**
     * Create an instance of {@link LoadForecastProfile }
     * 
     */
    public LoadForecastProfile createLoadForecastProfile() {
        return new LoadForecastProfile();
    }

    /**
     * Create an instance of {@link EnergyConsumer }
     * 
     */
    public EnergyConsumer createEnergyConsumer() {
        return new EnergyConsumer();
    }

    /**
     * Create an instance of {@link LoadControl }
     * 
     */
    public LoadControl createLoadControl() {
        return new LoadControl();
    }

    /**
     * Create an instance of {@link LoadReadingProfile }
     * 
     */
    public LoadReadingProfile createLoadReadingProfile() {
        return new LoadReadingProfile();
    }

    /**
     * Create an instance of {@link LoadControlProfile }
     * 
     */
    public LoadControlProfile createLoadControlProfile() {
        return new LoadControlProfile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadStatusProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "LoadStatusProfile")
    public JAXBElement<LoadStatusProfile> createLoadStatusProfile(LoadStatusProfile value) {
        return new JAXBElement<LoadStatusProfile>(_LoadStatusProfile_QNAME, LoadStatusProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "LoadControl")
    public JAXBElement<LoadControl> createLoadControl(LoadControl value) {
        return new JAXBElement<LoadControl>(_LoadControl_QNAME, LoadControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadForecastProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "LoadForecastProfile")
    public JAXBElement<LoadForecastProfile> createLoadForecastProfile(LoadForecastProfile value) {
        return new JAXBElement<LoadForecastProfile>(_LoadForecastProfile_QNAME, LoadForecastProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnergyConsumer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "EnergyConsumer")
    public JAXBElement<EnergyConsumer> createEnergyConsumer(EnergyConsumer value) {
        return new JAXBElement<EnergyConsumer>(_EnergyConsumer_QNAME, EnergyConsumer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadControlProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "LoadControlProfile")
    public JAXBElement<LoadControlProfile> createLoadControlProfile(LoadControlProfile value) {
        return new JAXBElement<LoadControlProfile>(_LoadControlProfile_QNAME, LoadControlProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadReadingProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", name = "LoadReadingProfile")
    public JAXBElement<LoadReadingProfile> createLoadReadingProfile(LoadReadingProfile value) {
        return new JAXBElement<LoadReadingProfile>(_LoadReadingProfile_QNAME, LoadReadingProfile.class, null, value);
    }

}
