/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:39 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.interchangemodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.ExecutionKind;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.MarketKind;


/**
 * This class represent an actual instance of a planned market. For example, a Day Ahead market opens with the Bid Submission, ends with the closing of the Bid Submission. The market run represent the whole process. MarketRuns can be defined for markets such as Day Ahead Market, Real Time Market, Hour Ahead Market, Week Ahead Market,...
 * 
 * <p>Java class for MarketRun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketRun">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executionType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}ExecutionKind" minOccurs="0"/>
 *         &lt;element name="marketEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="marketID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="marketRunID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="marketStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="marketType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}MarketKind" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketRun", propOrder = {
    "executionType",
    "marketEndTime",
    "marketID",
    "marketRunID",
    "marketStartTime",
    "marketType"
})
public class MarketRun {

    @XmlSchemaType(name = "string")
    protected ExecutionKind executionType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar marketEndTime;
    protected String marketID;
    protected String marketRunID;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar marketStartTime;
    @XmlSchemaType(name = "string")
    protected MarketKind marketType;

    /**
     * Gets the value of the executionType property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionKind }
     *     
     */
    public ExecutionKind getExecutionType() {
        return executionType;
    }

    /**
     * Sets the value of the executionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionKind }
     *     
     */
    public void setExecutionType(ExecutionKind value) {
        this.executionType = value;
    }

    /**
     * Gets the value of the marketEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarketEndTime() {
        return marketEndTime;
    }

    /**
     * Sets the value of the marketEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarketEndTime(XMLGregorianCalendar value) {
        this.marketEndTime = value;
    }

    /**
     * Gets the value of the marketID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketID() {
        return marketID;
    }

    /**
     * Sets the value of the marketID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketID(String value) {
        this.marketID = value;
    }

    /**
     * Gets the value of the marketRunID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketRunID() {
        return marketRunID;
    }

    /**
     * Sets the value of the marketRunID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketRunID(String value) {
        this.marketRunID = value;
    }

    /**
     * Gets the value of the marketStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarketStartTime() {
        return marketStartTime;
    }

    /**
     * Sets the value of the marketStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarketStartTime(XMLGregorianCalendar value) {
        this.marketStartTime = value;
    }

    /**
     * Gets the value of the marketType property.
     * 
     * @return
     *     possible object is
     *     {@link MarketKind }
     *     
     */
    public MarketKind getMarketType() {
        return marketType;
    }

    /**
     * Sets the value of the marketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketKind }
     *     
     */
    public void setMarketType(MarketKind value) {
        this.marketType = value;
    }

}
