//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 11:19:49 AM EST 
//


package com.omnetric.telecomdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.omnetric.telecomdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TelecomData_QNAME = new QName("http://www.omnetric.com/TelecomData.xsd#", "TelecomData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.omnetric.telecomdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TelecomData }
     * 
     */
    public TelecomData createTelecomData() {
        return new TelecomData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelecomData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omnetric.com/TelecomData.xsd#", name = "TelecomData")
    public JAXBElement<TelecomData> createTelecomData(TelecomData value) {
        return new JAXBElement<TelecomData>(_TelecomData_QNAME, TelecomData.class, null, value);
    }

}
