//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:51 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.reclosermodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for RecloserEventProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecloserEventProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="Recloser" type="{http://openfmb.org/xsd/2015/12/openfmb/reclosermodule}Recloser"/>
 *         &lt;element name="RecloserStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/reclosermodule}RecloserStatus"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecloserEventProfile", propOrder = {
    "recloser",
    "recloserStatus"
})
public class RecloserEventProfile
    extends Container
{

    @XmlElement(name = "Recloser", required = true)
    protected Recloser recloser;
    @XmlElement(name = "RecloserStatus", required = true)
    protected RecloserStatus recloserStatus;

    /**
     * Gets the value of the recloser property.
     * 
     * @return
     *     possible object is
     *     {@link Recloser }
     *     
     */
    public Recloser getRecloser() {
        return recloser;
    }

    /**
     * Sets the value of the recloser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recloser }
     *     
     */
    public void setRecloser(Recloser value) {
        this.recloser = value;
    }

    /**
     * Gets the value of the recloserStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RecloserStatus }
     *     
     */
    public RecloserStatus getRecloserStatus() {
        return recloserStatus;
    }

    /**
     * Sets the value of the recloserStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecloserStatus }
     *     
     */
    public void setRecloserStatus(RecloserStatus value) {
        this.recloserStatus = value;
    }

}
