//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:51 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.reclosermodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Status;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.SwitchStatusKind;


/**
 * <p>Java class for RecloserStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecloserStatus">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Status">
 *       &lt;sequence>
 *         &lt;element name="isBlocked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="switchStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}SwitchStatusKind" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecloserStatus", propOrder = {
    "isBlocked",
    "switchStatus"
})
public class RecloserStatus
    extends Status
{

    protected Boolean isBlocked;
    @XmlSchemaType(name = "string")
    protected SwitchStatusKind switchStatus;

    /**
     * Gets the value of the isBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBlocked() {
        return isBlocked;
    }

    /**
     * Sets the value of the isBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBlocked(Boolean value) {
        this.isBlocked = value;
    }

    /**
     * Gets the value of the switchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchStatusKind }
     *     
     */
    public SwitchStatusKind getSwitchStatus() {
        return switchStatus;
    }

    /**
     * Sets the value of the switchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchStatusKind }
     *     
     */
    public void setSwitchStatus(SwitchStatusKind value) {
        this.switchStatus = value;
    }

}
