/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:03:32 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.generationmodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2015._12.openfmb.generationmodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GenerationControl_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationControl");
    private final static QName _GenerationStatus_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationStatus");
    private final static QName _GenerationForecastProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationForecastProfile");
    private final static QName _GenerationEventProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationEventProfile");
    private final static QName _GeneratingUnit_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GeneratingUnit");
    private final static QName _GenerationControlProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationControlProfile");
    private final static QName _GenerationReadingProfile_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/generationmodule", "GenerationReadingProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2015._12.openfmb.generationmodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerationReadingProfile }
     * 
     */
    public GenerationReadingProfile createGenerationReadingProfile() {
        return new GenerationReadingProfile();
    }

    /**
     * Create an instance of {@link GenerationControlProfile }
     * 
     */
    public GenerationControlProfile createGenerationControlProfile() {
        return new GenerationControlProfile();
    }

    /**
     * Create an instance of {@link GenerationControl }
     * 
     */
    public GenerationControl createGenerationControl() {
        return new GenerationControl();
    }

    /**
     * Create an instance of {@link GeneratingUnit }
     * 
     */
    public GeneratingUnit createGeneratingUnit() {
        return new GeneratingUnit();
    }

    /**
     * Create an instance of {@link GenerationEventProfile }
     * 
     */
    public GenerationEventProfile createGenerationEventProfile() {
        return new GenerationEventProfile();
    }

    /**
     * Create an instance of {@link GenerationStatus }
     * 
     */
    public GenerationStatus createGenerationStatus() {
        return new GenerationStatus();
    }

    /**
     * Create an instance of {@link GenerationForecastProfile }
     * 
     */
    public GenerationForecastProfile createGenerationForecastProfile() {
        return new GenerationForecastProfile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationControl")
    public JAXBElement<GenerationControl> createGenerationControl(GenerationControl value) {
        return new JAXBElement<GenerationControl>(_GenerationControl_QNAME, GenerationControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationStatus")
    public JAXBElement<GenerationStatus> createGenerationStatus(GenerationStatus value) {
        return new JAXBElement<GenerationStatus>(_GenerationStatus_QNAME, GenerationStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationForecastProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationForecastProfile")
    public JAXBElement<GenerationForecastProfile> createGenerationForecastProfile(GenerationForecastProfile value) {
        return new JAXBElement<GenerationForecastProfile>(_GenerationForecastProfile_QNAME, GenerationForecastProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationEventProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationEventProfile")
    public JAXBElement<GenerationEventProfile> createGenerationEventProfile(GenerationEventProfile value) {
        return new JAXBElement<GenerationEventProfile>(_GenerationEventProfile_QNAME, GenerationEventProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratingUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GeneratingUnit")
    public JAXBElement<GeneratingUnit> createGeneratingUnit(GeneratingUnit value) {
        return new JAXBElement<GeneratingUnit>(_GeneratingUnit_QNAME, GeneratingUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationControlProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationControlProfile")
    public JAXBElement<GenerationControlProfile> createGenerationControlProfile(GenerationControlProfile value) {
        return new JAXBElement<GenerationControlProfile>(_GenerationControlProfile_QNAME, GenerationControlProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerationReadingProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/generationmodule", name = "GenerationReadingProfile")
    public JAXBElement<GenerationReadingProfile> createGenerationReadingProfile(GenerationReadingProfile value) {
        return new JAXBElement<GenerationReadingProfile>(_GenerationReadingProfile_QNAME, GenerationReadingProfile.class, null, value);
    }

}
