/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.solarmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for SolarEventProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolarEventProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="SolarInverter" type="{http://openfmb.org/xsd/2015/12/openfmb/solarmodule}SolarInverter"/>
 *         &lt;element name="SolarInverterStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/solarmodule}SolarInverterStatus"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolarEventProfile", propOrder = {
    "solarInverter",
    "solarInverterStatus"
})
public class SolarEventProfile
    extends Container
{

    @XmlElement(name = "SolarInverter", required = true)
    protected SolarInverter solarInverter;
    @XmlElement(name = "SolarInverterStatus", required = true)
    protected SolarInverterStatus solarInverterStatus;

    /**
     * Gets the value of the solarInverter property.
     * 
     * @return
     *     possible object is
     *     {@link SolarInverter }
     *     
     */
    public SolarInverter getSolarInverter() {
        return solarInverter;
    }

    /**
     * Sets the value of the solarInverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolarInverter }
     *     
     */
    public void setSolarInverter(SolarInverter value) {
        this.solarInverter = value;
    }

    /**
     * Gets the value of the solarInverterStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SolarInverterStatus }
     *     
     */
    public SolarInverterStatus getSolarInverterStatus() {
        return solarInverterStatus;
    }

    /**
     * Sets the value of the solarInverterStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolarInverterStatus }
     *     
     */
    public void setSolarInverterStatus(SolarInverterStatus value) {
        this.solarInverterStatus = value;
    }

}
