//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.solarmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SolarCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolarCapability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ahrRtg" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="qualityFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="voltage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="wRtgMaxVal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="wRtgMinVal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolarCapability", propOrder = {
    "ahrRtg",
    "qualityFlag",
    "timestamp",
    "voltage",
    "wRtgMaxVal",
    "wRtgMinVal"
})
public class SolarCapability {

    protected Float ahrRtg;
    protected String qualityFlag;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    protected Float voltage;
    protected Float wRtgMaxVal;
    protected Float wRtgMinVal;

    /**
     * Gets the value of the ahrRtg property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAhrRtg() {
        return ahrRtg;
    }

    /**
     * Sets the value of the ahrRtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAhrRtg(Float value) {
        this.ahrRtg = value;
    }

    /**
     * Gets the value of the qualityFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityFlag() {
        return qualityFlag;
    }

    /**
     * Sets the value of the qualityFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityFlag(String value) {
        this.qualityFlag = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVoltage(Float value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the wRtgMaxVal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWRtgMaxVal() {
        return wRtgMaxVal;
    }

    /**
     * Sets the value of the wRtgMaxVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWRtgMaxVal(Float value) {
        this.wRtgMaxVal = value;
    }

    /**
     * Gets the value of the wRtgMinVal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWRtgMinVal() {
        return wRtgMinVal;
    }

    /**
     * Sets the value of the wRtgMinVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWRtgMinVal(Float value) {
        this.wRtgMinVal = value;
    }

}
