//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:04:19 AM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.solarmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openfmb.xsd._2015._12.openfmb.commonmodule.Container;


/**
 * <p>Java class for SolarControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolarControlProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container">
 *       &lt;sequence>
 *         &lt;element name="SolarControl" type="{http://openfmb.org/xsd/2015/12/openfmb/solarmodule}SolarControl"/>
 *         &lt;element name="SolarInverter" type="{http://openfmb.org/xsd/2015/12/openfmb/solarmodule}SolarInverter"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolarControlProfile", propOrder = {
    "solarControl",
    "solarInverter"
})
public class SolarControlProfile
    extends Container
{

    @XmlElement(name = "SolarControl", required = true)
    protected SolarControl solarControl;
    @XmlElement(name = "SolarInverter", required = true)
    protected SolarInverter solarInverter;

    /**
     * Gets the value of the solarControl property.
     * 
     * @return
     *     possible object is
     *     {@link SolarControl }
     *     
     */
    public SolarControl getSolarControl() {
        return solarControl;
    }

    /**
     * Sets the value of the solarControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolarControl }
     *     
     */
    public void setSolarControl(SolarControl value) {
        this.solarControl = value;
    }

    /**
     * Gets the value of the solarInverter property.
     * 
     * @return
     *     possible object is
     *     {@link SolarInverter }
     *     
     */
    public SolarInverter getSolarInverter() {
        return solarInverter;
    }

    /**
     * Sets the value of the solarInverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolarInverter }
     *     
     */
    public void setSolarInverter(SolarInverter value) {
        this.solarInverter = value;
    }

}
