/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Multi-purpose data points for defining a curve.  The use of this generic class is discouraged if a more specific class  can be used to specify the x and y axis values along with their specific data types.
 * 
 * <p>Java class for CurveData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurveData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xvalue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="y1value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="y2value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="y3value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurveData", propOrder = {
    "xvalue",
    "y1Value",
    "y2Value",
    "y3Value"
})
public class CurveData {

    protected Float xvalue;
    @XmlElement(name = "y1value")
    protected Float y1Value;
    @XmlElement(name = "y2value")
    protected Float y2Value;
    @XmlElement(name = "y3value")
    protected Float y3Value;

    /**
     * Gets the value of the xvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getXvalue() {
        return xvalue;
    }

    /**
     * Sets the value of the xvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setXvalue(Float value) {
        this.xvalue = value;
    }

    /**
     * Gets the value of the y1Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY1Value() {
        return y1Value;
    }

    /**
     * Sets the value of the y1Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY1Value(Float value) {
        this.y1Value = value;
    }

    /**
     * Gets the value of the y2Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY2Value() {
        return y2Value;
    }

    /**
     * Sets the value of the y2Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY2Value(Float value) {
        this.y2Value = value;
    }

    /**
     * Gets the value of the y3Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY3Value() {
        return y3Value;
    }

    /**
     * Sets the value of the y3Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY3Value(Float value) {
        this.y3Value = value;
    }

}
