/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Instructs an end device (or an end device group) to perform a specified action.
 * 
 * <p>Java class for EndDeviceControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndDeviceControl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issueID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduledInterval" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}DateTimeInterval" minOccurs="0"/>
 *         &lt;element name="EndDeviceControlType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}EndDeviceControlType" minOccurs="0"/>
 *         &lt;element name="SetPoints" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}SetPoint" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndDeviceControl", propOrder = {
    "issueID",
    "name",
    "scheduledInterval",
    "endDeviceControlType",
    "setPoints"
})
public class EndDeviceControl {

    protected String issueID;
    protected String name;
    protected DateTimeInterval scheduledInterval;
    @XmlElement(name = "EndDeviceControlType")
    protected EndDeviceControlType endDeviceControlType;
    @XmlElement(name = "SetPoints")
    protected List<SetPoint> setPoints;

    /**
     * Gets the value of the issueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueID() {
        return issueID;
    }

    /**
     * Sets the value of the issueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueID(String value) {
        this.issueID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the scheduledInterval property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeInterval }
     *     
     */
    public DateTimeInterval getScheduledInterval() {
        return scheduledInterval;
    }

    /**
     * Sets the value of the scheduledInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeInterval }
     *     
     */
    public void setScheduledInterval(DateTimeInterval value) {
        this.scheduledInterval = value;
    }

    /**
     * Gets the value of the endDeviceControlType property.
     * 
     * @return
     *     possible object is
     *     {@link EndDeviceControlType }
     *     
     */
    public EndDeviceControlType getEndDeviceControlType() {
        return endDeviceControlType;
    }

    /**
     * Sets the value of the endDeviceControlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndDeviceControlType }
     *     
     */
    public void setEndDeviceControlType(EndDeviceControlType value) {
        this.endDeviceControlType = value;
    }

    /**
     * Gets the value of the setPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetPoint }
     * 
     * 
     */
    public List<SetPoint> getSetPoints() {
        if (setPoints == null) {
            setPoints = new ArrayList<SetPoint>();
        }
        return this.setPoints;
    }

}
