//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketProductKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MarketProductKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="RD"/>
 *     &lt;enumeration value="SR"/>
 *     &lt;enumeration value="NR"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="LFU"/>
 *     &lt;enumeration value="REG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MarketProductKind")
@XmlEnum
public enum MarketProductKind {


    /**
     * energy type
     * 
     */
    EN,

    /**
     * regulation up
     * 
     */
    RU,

    /**
     * regulation down
     * 
     */
    RD,

    /**
     * spinning reserve
     * 
     */
    SR,

    /**
     * non spinning reserve
     * 
     */
    NR,

    /**
     * Residual Unit Commitment
     * 
     */
    RC,

    /**
     * Load following up
     * 
     */
    LFU,

    /**
     * Regulation
     * 
     */
    REG;

    public String value() {
        return name();
    }

    public static MarketProductKind fromValue(String v) {
        return valueOf(v);
    }

}
