//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Physical asset that performs the metering role of the usage point. Used for measuring consumption and detection of events.
 * 
 * <p>Java class for Meter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Meter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}IdentifiedObject">
 *       &lt;sequence>
 *         &lt;element name="PowerSystemResource" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}PowerSystemResource" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meter", propOrder = {
    "powerSystemResource"
})
public class Meter
    extends IdentifiedObject
{

    @XmlElement(name = "PowerSystemResource")
    protected PowerSystemResource powerSystemResource;

    /**
     * Gets the value of the powerSystemResource property.
     * 
     * @return
     *     possible object is
     *     {@link PowerSystemResource }
     *     
     */
    public PowerSystemResource getPowerSystemResource() {
        return powerSystemResource;
    }

    /**
     * Sets the value of the powerSystemResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerSystemResource }
     *     
     */
    public void setPowerSystemResource(PowerSystemResource value) {
        this.powerSystemResource = value;
    }

}
