/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfmb.xsd._2015._12.openfmb.commonmodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Container_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Container");
    private final static QName _ReadingType_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "ReadingType");
    private final static QName _ActivePower_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "ActivePower");
    private final static QName _EndDeviceControlType_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "EndDeviceControlType");
    private final static QName _ForecastSchedule_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "ForecastSchedule");
    private final static QName _Meter_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Meter");
    private final static QName _BooleanMeasurementValue_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "BooleanMeasurementValue");
    private final static QName _SetPoint_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "SetPoint");
    private final static QName _EndDeviceControl_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "EndDeviceControl");
    private final static QName _AnalogValue_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "AnalogValue");
    private final static QName _StringMeasurement_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "StringMeasurement");
    private final static QName _Reading_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Reading");
    private final static QName _Analog_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Analog");
    private final static QName _BasicIntervalSchedule_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "BasicIntervalSchedule");
    private final static QName _Event_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Event");
    private final static QName _Discrete_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Discrete");
    private final static QName _IdentifiedObject_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "IdentifiedObject");
    private final static QName _PowerSystemResource_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "PowerSystemResource");
    private final static QName _CurveData_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "CurveData");
    private final static QName _BooleanMeasurement_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "BooleanMeasurement");
    private final static QName _Status_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Status");
    private final static QName _StringMeasurementValue_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "StringMeasurementValue");
    private final static QName _Curve_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Curve");
    private final static QName _DateTimeInterval_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "DateTimeInterval");
    private final static QName _DiscreteValue_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "DiscreteValue");
    private final static QName _IrregularTimePoint_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "IrregularTimePoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfmb.xsd._2015._12.openfmb.commonmodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EndDeviceControlType }
     * 
     */
    public EndDeviceControlType createEndDeviceControlType() {
        return new EndDeviceControlType();
    }

    /**
     * Create an instance of {@link ForecastSchedule }
     * 
     */
    public ForecastSchedule createForecastSchedule() {
        return new ForecastSchedule();
    }

    /**
     * Create an instance of {@link Meter }
     * 
     */
    public Meter createMeter() {
        return new Meter();
    }

    /**
     * Create an instance of {@link BooleanMeasurementValue }
     * 
     */
    public BooleanMeasurementValue createBooleanMeasurementValue() {
        return new BooleanMeasurementValue();
    }

    /**
     * Create an instance of {@link SetPoint }
     * 
     */
    public SetPoint createSetPoint() {
        return new SetPoint();
    }

    /**
     * Create an instance of {@link EndDeviceControl }
     * 
     */
    public EndDeviceControl createEndDeviceControl() {
        return new EndDeviceControl();
    }

    /**
     * Create an instance of {@link AnalogValue }
     * 
     */
    public AnalogValue createAnalogValue() {
        return new AnalogValue();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link ReadingType }
     * 
     */
    public ReadingType createReadingType() {
        return new ReadingType();
    }

    /**
     * Create an instance of {@link ActivePower }
     * 
     */
    public ActivePower createActivePower() {
        return new ActivePower();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link StringMeasurementValue }
     * 
     */
    public StringMeasurementValue createStringMeasurementValue() {
        return new StringMeasurementValue();
    }

    /**
     * Create an instance of {@link Curve }
     * 
     */
    public Curve createCurve() {
        return new Curve();
    }

    /**
     * Create an instance of {@link DateTimeInterval }
     * 
     */
    public DateTimeInterval createDateTimeInterval() {
        return new DateTimeInterval();
    }

    /**
     * Create an instance of {@link DiscreteValue }
     * 
     */
    public DiscreteValue createDiscreteValue() {
        return new DiscreteValue();
    }

    /**
     * Create an instance of {@link IrregularTimePoint }
     * 
     */
    public IrregularTimePoint createIrregularTimePoint() {
        return new IrregularTimePoint();
    }

    /**
     * Create an instance of {@link StringMeasurement }
     * 
     */
    public StringMeasurement createStringMeasurement() {
        return new StringMeasurement();
    }

    /**
     * Create an instance of {@link Reading }
     * 
     */
    public Reading createReading() {
        return new Reading();
    }

    /**
     * Create an instance of {@link Analog }
     * 
     */
    public Analog createAnalog() {
        return new Analog();
    }

    /**
     * Create an instance of {@link BasicIntervalSchedule }
     * 
     */
    public BasicIntervalSchedule createBasicIntervalSchedule() {
        return new BasicIntervalSchedule();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Discrete }
     * 
     */
    public Discrete createDiscrete() {
        return new Discrete();
    }

    /**
     * Create an instance of {@link IdentifiedObject }
     * 
     */
    public IdentifiedObject createIdentifiedObject() {
        return new IdentifiedObject();
    }

    /**
     * Create an instance of {@link PowerSystemResource }
     * 
     */
    public PowerSystemResource createPowerSystemResource() {
        return new PowerSystemResource();
    }

    /**
     * Create an instance of {@link CurveData }
     * 
     */
    public CurveData createCurveData() {
        return new CurveData();
    }

    /**
     * Create an instance of {@link BooleanMeasurement }
     * 
     */
    public BooleanMeasurement createBooleanMeasurement() {
        return new BooleanMeasurement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Container }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Container")
    public JAXBElement<Container> createContainer(Container value) {
        return new JAXBElement<Container>(_Container_QNAME, Container.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "ReadingType")
    public JAXBElement<ReadingType> createReadingType(ReadingType value) {
        return new JAXBElement<ReadingType>(_ReadingType_QNAME, ReadingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivePower }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "ActivePower")
    public JAXBElement<ActivePower> createActivePower(ActivePower value) {
        return new JAXBElement<ActivePower>(_ActivePower_QNAME, ActivePower.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceControlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "EndDeviceControlType")
    public JAXBElement<EndDeviceControlType> createEndDeviceControlType(EndDeviceControlType value) {
        return new JAXBElement<EndDeviceControlType>(_EndDeviceControlType_QNAME, EndDeviceControlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForecastSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "ForecastSchedule")
    public JAXBElement<ForecastSchedule> createForecastSchedule(ForecastSchedule value) {
        return new JAXBElement<ForecastSchedule>(_ForecastSchedule_QNAME, ForecastSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Meter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Meter")
    public JAXBElement<Meter> createMeter(Meter value) {
        return new JAXBElement<Meter>(_Meter_QNAME, Meter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanMeasurementValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "BooleanMeasurementValue")
    public JAXBElement<BooleanMeasurementValue> createBooleanMeasurementValue(BooleanMeasurementValue value) {
        return new JAXBElement<BooleanMeasurementValue>(_BooleanMeasurementValue_QNAME, BooleanMeasurementValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "SetPoint")
    public JAXBElement<SetPoint> createSetPoint(SetPoint value) {
        return new JAXBElement<SetPoint>(_SetPoint_QNAME, SetPoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "EndDeviceControl")
    public JAXBElement<EndDeviceControl> createEndDeviceControl(EndDeviceControl value) {
        return new JAXBElement<EndDeviceControl>(_EndDeviceControl_QNAME, EndDeviceControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnalogValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "AnalogValue")
    public JAXBElement<AnalogValue> createAnalogValue(AnalogValue value) {
        return new JAXBElement<AnalogValue>(_AnalogValue_QNAME, AnalogValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringMeasurement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "StringMeasurement")
    public JAXBElement<StringMeasurement> createStringMeasurement(StringMeasurement value) {
        return new JAXBElement<StringMeasurement>(_StringMeasurement_QNAME, StringMeasurement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reading }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Reading")
    public JAXBElement<Reading> createReading(Reading value) {
        return new JAXBElement<Reading>(_Reading_QNAME, Reading.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Analog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Analog")
    public JAXBElement<Analog> createAnalog(Analog value) {
        return new JAXBElement<Analog>(_Analog_QNAME, Analog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicIntervalSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "BasicIntervalSchedule")
    public JAXBElement<BasicIntervalSchedule> createBasicIntervalSchedule(BasicIntervalSchedule value) {
        return new JAXBElement<BasicIntervalSchedule>(_BasicIntervalSchedule_QNAME, BasicIntervalSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Event }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Event")
    public JAXBElement<Event> createEvent(Event value) {
        return new JAXBElement<Event>(_Event_QNAME, Event.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Discrete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Discrete")
    public JAXBElement<Discrete> createDiscrete(Discrete value) {
        return new JAXBElement<Discrete>(_Discrete_QNAME, Discrete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifiedObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "IdentifiedObject")
    public JAXBElement<IdentifiedObject> createIdentifiedObject(IdentifiedObject value) {
        return new JAXBElement<IdentifiedObject>(_IdentifiedObject_QNAME, IdentifiedObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerSystemResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "PowerSystemResource")
    public JAXBElement<PowerSystemResource> createPowerSystemResource(PowerSystemResource value) {
        return new JAXBElement<PowerSystemResource>(_PowerSystemResource_QNAME, PowerSystemResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurveData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "CurveData")
    public JAXBElement<CurveData> createCurveData(CurveData value) {
        return new JAXBElement<CurveData>(_CurveData_QNAME, CurveData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanMeasurement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "BooleanMeasurement")
    public JAXBElement<BooleanMeasurement> createBooleanMeasurement(BooleanMeasurement value) {
        return new JAXBElement<BooleanMeasurement>(_BooleanMeasurement_QNAME, BooleanMeasurement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringMeasurementValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "StringMeasurementValue")
    public JAXBElement<StringMeasurementValue> createStringMeasurementValue(StringMeasurementValue value) {
        return new JAXBElement<StringMeasurementValue>(_StringMeasurementValue_QNAME, StringMeasurementValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Curve }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Curve")
    public JAXBElement<Curve> createCurve(Curve value) {
        return new JAXBElement<Curve>(_Curve_QNAME, Curve.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeInterval }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "DateTimeInterval")
    public JAXBElement<DateTimeInterval> createDateTimeInterval(DateTimeInterval value) {
        return new JAXBElement<DateTimeInterval>(_DateTimeInterval_QNAME, DateTimeInterval.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiscreteValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "DiscreteValue")
    public JAXBElement<DiscreteValue> createDiscreteValue(DiscreteValue value) {
        return new JAXBElement<DiscreteValue>(_DiscreteValue_QNAME, DiscreteValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IrregularTimePoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "IrregularTimePoint")
    public JAXBElement<IrregularTimePoint> createIrregularTimePoint(IrregularTimePoint value) {
        return new JAXBElement<IrregularTimePoint>(_IrregularTimePoint_QNAME, IrregularTimePoint.class, null, value);
    }

}
