/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhaseCodeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PhaseCodeKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="AB"/>
 *     &lt;enumeration value="ABC"/>
 *     &lt;enumeration value="ABCN"/>
 *     &lt;enumeration value="ABN"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="ACN"/>
 *     &lt;enumeration value="AN"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="BC"/>
 *     &lt;enumeration value="BCN"/>
 *     &lt;enumeration value="BN"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="noPhase"/>
 *     &lt;enumeration value="s1"/>
 *     &lt;enumeration value="s12"/>
 *     &lt;enumeration value="s12N"/>
 *     &lt;enumeration value="s1N"/>
 *     &lt;enumeration value="s2"/>
 *     &lt;enumeration value="s2N"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PhaseCodeKind")
@XmlEnum
public enum PhaseCodeKind {


    /**
     * Phase A.
     * 
     */
    A("A"),

    /**
     * Phases A and B.
     * 
     */
    AB("AB"),

    /**
     * Phases A, B, and C.
     * 
     */
    ABC("ABC"),

    /**
     * Phases A, B, C, and N.
     * 
     */
    ABCN("ABCN"),

    /**
     * Phases A, B, and neutral.
     * 
     */
    ABN("ABN"),

    /**
     * Phases A and C.
     * 
     */
    AC("AC"),

    /**
     * Phases A, C and neutral.
     * 
     */
    ACN("ACN"),

    /**
     * Phases A and neutral.
     * 
     */
    AN("AN"),

    /**
     * Phase B.
     * 
     */
    B("B"),

    /**
     * Phases B and C.
     * 
     */
    BC("BC"),

    /**
     * Phases B, C, and neutral.
     * 
     */
    BCN("BCN"),

    /**
     * Phases B and neutral.
     * 
     */
    BN("BN"),

    /**
     * Phase C.
     * 
     */
    C("C"),

    /**
     * Phases C and neutral.
     * 
     */
    CN("CN"),

    /**
     * Neutral phase.
     * 
     */
    N("N"),

    /**
     * Not applicable
     * 
     */
    @XmlEnumValue("noPhase")
    NO_PHASE("noPhase"),

    /**
     * Secondary phase 1.
     * 
     */
    @XmlEnumValue("s1")
    S_1("s1"),

    /**
     * Secondary phase 1 and 2.
     * 
     */
    @XmlEnumValue("s12")
    S_12("s12"),

    /**
     * Secondary phases 1, 2, and neutral.
     * 
     */
    @XmlEnumValue("s12N")
    S_12_N("s12N"),

    /**
     * Secondary phase 1 and neutral.
     * 
     */
    @XmlEnumValue("s1N")
    S_1_N("s1N"),

    /**
     * Secondary phase 2.
     * 
     */
    @XmlEnumValue("s2")
    S_2("s2"),

    /**
     * Secondary phase 2 and neutral.
     * 
     */
    @XmlEnumValue("s2N")
    S_2_N("s2N");
    private final String value;

    PhaseCodeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PhaseCodeKind fromValue(String v) {
        for (PhaseCodeKind c: PhaseCodeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
