/**
 * Copyright 2016 Duke Energy.
 *
 * Licensed to Duke Energy (www.duke-energy.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Duke Energy
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 08:43:06 PM EDT 
//


package org.openfmb.xsd._2015._12.openfmb.commonmodule;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitSymbolKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitSymbolKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Amp"/>
 *     &lt;enumeration value="deg"/>
 *     &lt;enumeration value="degC"/>
 *     &lt;enumeration value="degF"/>
 *     &lt;enumeration value="Farad"/>
 *     &lt;enumeration value="gram"/>
 *     &lt;enumeration value="hour"/>
 *     &lt;enumeration value="Henry"/>
 *     &lt;enumeration value="Hz"/>
 *     &lt;enumeration value="Joule"/>
 *     &lt;enumeration value="meter"/>
 *     &lt;enumeration value="m2"/>
 *     &lt;enumeration value="m3"/>
 *     &lt;enumeration value="min"/>
 *     &lt;enumeration value="mph"/>
 *     &lt;enumeration value="Newton"/>
 *     &lt;enumeration value="noUnit"/>
 *     &lt;enumeration value="ohm"/>
 *     &lt;enumeration value="Pa"/>
 *     &lt;enumeration value="rad"/>
 *     &lt;enumeration value="Siemens"/>
 *     &lt;enumeration value="sec"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="VA"/>
 *     &lt;enumeration value="VAh"/>
 *     &lt;enumeration value="VAr"/>
 *     &lt;enumeration value="VArh"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="Wh"/>
 *     &lt;enumeration value="wPerVA"/>
 *     &lt;enumeration value="WPerM2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitSymbolKind")
@XmlEnum
public enum UnitSymbolKind {


    /**
     * Current in ampere.
     * 
     */
    @XmlEnumValue("Amp")
    AMP("Amp"),

    /**
     * Plane angle in degrees.
     * 
     */
    @XmlEnumValue("deg")
    DEG("deg"),

    /**
     * Relative temperature in degrees Celsius. In the SI unit system the symbol is ºC. Electric charge is measured in coulomb that has the unit symbol C. To distinguish degree Celsius form coulomb the symbol used in the UML is degC. Reason for not using ºC is the special character º is difficult to manage in software.
     * 
     */
    @XmlEnumValue("degC")
    DEG_C("degC"),

    /**
     * Relative temperature in degree fahrenheit.
     * 
     */
    @XmlEnumValue("degF")
    DEG_F("degF"),

    /**
     * Capacitance in farad.
     * 
     */
    @XmlEnumValue("Farad")
    FARAD("Farad"),

    /**
     * Mass in gram.
     * 
     */
    @XmlEnumValue("gram")
    GRAM("gram"),

    /**
     * Time in hours.
     * 
     */
    @XmlEnumValue("hour")
    HOUR("hour"),

    /**
     * Inductance in henry.
     * 
     */
    @XmlEnumValue("Henry")
    HENRY("Henry"),

    /**
     * Frequency in hertz.
     * 
     */
    @XmlEnumValue("Hz")
    HZ("Hz"),

    /**
     * Energy in joule.
     * 
     */
    @XmlEnumValue("Joule")
    JOULE("Joule"),

    /**
     * Length in meter.
     * 
     */
    @XmlEnumValue("meter")
    METER("meter"),

    /**
     * Area in square meters.
     * 
     */
    @XmlEnumValue("m2")
    M_2("m2"),

    /**
     * Volume in cubic meters.
     * 
     */
    @XmlEnumValue("m3")
    M_3("m3"),

    /**
     * Time in minutes.
     * 
     */
    @XmlEnumValue("min")
    MIN("min"),

    /**
     * Mile per hour
     * 
     */
    @XmlEnumValue("mph")
    MPH("mph"),

    /**
     * Force in newton.
     * 
     */
    @XmlEnumValue("Newton")
    NEWTON("Newton"),

    /**
     * Dimension less quantity, e.g. count, per unit, etc.
     * 
     */
    @XmlEnumValue("noUnit")
    NO_UNIT("noUnit"),

    /**
     * Resistance in ohm.
     * 
     */
    @XmlEnumValue("ohm")
    OHM("ohm"),

    /**
     * Pressure in pascal (n/m2).
     * 
     */
    @XmlEnumValue("Pa")
    PA("Pa"),

    /**
     * Plane angle in radians.
     * 
     */
    @XmlEnumValue("rad")
    RAD("rad"),

    /**
     * Conductance in siemens.
     * 
     */
    @XmlEnumValue("Siemens")
    SIEMENS("Siemens"),

    /**
     * Time in seconds.
     * 
     */
    @XmlEnumValue("sec")
    SEC("sec"),

    /**
     * Voltage in volt.
     * 
     */
    V("V"),

    /**
     * Apparent power in volt ampere.
     * 
     */
    VA("VA"),

    /**
     * Apparent energy in volt ampere hours.
     * 
     */
    @XmlEnumValue("VAh")
    V_AH("VAh"),

    /**
     * Reactive power in volt ampere reactive.
     * 
     */
    @XmlEnumValue("VAr")
    V_AR("VAr"),

    /**
     * Reactive energy in volt ampere reactive hours.
     * 
     */
    @XmlEnumValue("VArh")
    V_ARH("VArh"),

    /**
     * Active power in watt.
     * 
     */
    W("W"),

    /**
     * Real energy in what hours.
     * 
     */
    @XmlEnumValue("Wh")
    WH("Wh"),

    /**
     * Power factor
     * 
     */
    @XmlEnumValue("wPerVA")
    W_PER_VA("wPerVA"),

    /**
     * Watts per square meter
     * 
     */
    @XmlEnumValue("WPerM2")
    W_PER_M_2("WPerM2");
    private final String value;

    UnitSymbolKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitSymbolKind fromValue(String v) {
        for (UnitSymbolKind c: UnitSymbolKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
